#!/bin/bash

#SBATCH -A bsc20
#SBATCH --job-name=output_vae
#SBATCH --output=err_out/output_vae_%j.out
#SBATCH --error=err_out/output_vae_%j.err
#SBATCH --qos=gp_bscls
#SBATCH -c 16
#SBATCH --time=00-00:15:00
#SBATCH -D .

data_path=$1
metadata_path=$2
vae_path=$3
recnet_path=$4
output_rec_path=$5
output_path=$6

module load intel impi mkl hdf5 python
PYTHONPATH=$PYTHONPATH:.
python src/get_vae_outputs.py --data_path $data_path \
                             --metadata_path $metadata_path \
                             --model_path $vae_path \
                             --recnet_path $recnet_path \
                             --recnet_hyperparams_path ${output_rec_path}/best_hyperparameters.csv \
                             --output_path $output_path \
                             --seed 2023