#!/bin/bash

#SBATCH -A bsc20
#SBATCH --job-name=consensuscluster
#SBATCH --output=err_out/consensuscluster_%j.out
#SBATCH --error=err_out/consensuscluster_%j.err
#SBATCH --qos=gp_bscls
#SBATCH -c 16
#SBATCH --time=00-02:00:00
#SBATCH -D .

data_path=$1
metadata_path=$2
save_path=$3
real_space=$4
module load intel R
if [ "$real_space" == "true" ]; then
  Rscript src/g3g4_clustering.R --data_path "$data_path" \
                                --metadata_path "$metadata_path" \
                                --clusterAlg "km" \
                                --real_space \
                                --save_path "$save_path" \
                                --plot_ext "pdf" \
                                --reps 1000 \
                                --psamples 0.8 \
                                --pfeatures 1 \
                                --maxk 3
else
  Rscript src/g3g4_clustering.R --data_path "$data_path" \
                                --metadata_path "$metadata_path" \
                                --clusterAlg "km" \
                                --save_path "$save_path" \
                                --plot_ext "pdf" \
                                --reps 1000 \
                                --psamples 0.8 \
                                --pfeatures 1 \
                                --maxk 3
fi

module purge
module load intel impi mkl hdf5 python
export PYTHONPATH=$PYTHONPATH:.
python src/consensuscluster_analysis.py --data_path $data_path \
                                                                   --metadata_path $metadata_path \
                                                                   --consensus_path ${save_path}/km/ \
                                                                   --save_path ${save_path}/km/