#!/bin/bash

#SBATCH -A bsc20
#SBATCH --job-name=augment
#SBATCH --output=err_out/augment_%j.out
#SBATCH --error=err_out/augment_%j.err
#SBATCH --qos=gp_bscls
#SBATCH -c 16
#SBATCH --time=00-00:30:00
#SBATCH -D .

data_path=$1
metadata_path=$2
vae_path=$3
recnet_path=$4
output_rec_path=$5
group_to_augment=$6
n_synth=$7
save_path=$8
module load intel impi mkl hdf5 python
PYTHONPATH=$PYTHONPATH:.
python src/data_augmentation.py --data_path $data_path \
                           --clinical_path $metadata_path \
                           --model_path $vae_path \
                           --network_model_path $recnet_path \
                           --recnet_hyperparams_path ${output_rec_path}/best_hyperparameters.csv \
                           --mu 0 \
                           --std 1 \
                           --noise_ratio 0.25 \
                           --group_to_augment "${group_to_augment}" \
                           --n_synth $n_synth \
                           --results_path $save_path