#!/bin/bash

#SBATCH -A bsc20
#SBATCH --qos=gp_bscls
#SBATCH --job-name=shap_medulloblastoma
#SBATCH -D .
#SBATCH --output=err_out/shap_%j.out
#SBATCH --error=err_out/shap_%j.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=112
#SBATCH --hint=nomultithread
#SBATCH --time=01-00:00:00
#SBATCH --constraint=highmem


# This is for amd: #SBATCH --job-name=shap_amd
# This is for amd: #SBATCH -D .
# This is for amd: #SBATCH --output=shap_amd_%j.out
# This is for amd: #SBATCH --error=shap_amd_%j.err
# This is for amd: #SBATCH --ntasks=1
# This is for amd: #SBATCH --cpus-per-task=128
# This is for amd: #SBATCH --time=00-00:30:00
# This is for amd: #SBATCH --qos=debug

num_classes=$1
data_path=$2
clinical_path=$3
model_path=$4
save_path=$5
group_to_analyze=$6
# MN5:
module load miniconda
conda init
# CTE-AMD:
#module load anaconda
#eval "$(conda shell.bash hook)"
# Common:
conda activate ml_gpc

# Set NUMEXPR_MAX_THREADS to match the number of threads
export NUMEXPR_MAX_THREADS=128

export PYTHONPATH=$PYTHONPATH:.
# command for testing
#python src/classification_shap.py --n_shap 2 \
#                                  --qval 0.95 \
#                                  --num_classes $num_classes \
#                                  --n_trials 2 \
#                                  --n_br 2 \
#                                  --tree_method exact \
#                                  --data_path $data_path \
#                                  --clinical_path $clinical_path \
#                                  --model_path $model_path \
#                                  --save_path $save_path \
#                                  --group_to_analyze "${group_to_analyze}"
#exit 1
# command for full job
python src/classification_shap.py --n_shap 100 \
                                  --qval 0.95 \
                                  --num_classes $num_classes \
                                  --n_trials 100 \
                                  --n_br 100 \
                                  --tree_method exact \
                                  --data_path $data_path \
                                  --clinical_path $clinical_path \
                                  --model_path $model_path \
                                  --save_path $save_path \
                                  --group_to_analyze "${group_to_analyze}"
#                                  --top_n_lv 10
#--data_path data/interim/20240301_Mahalanobis/cavalli.csv \
#--clinical_path data/cavalli_subgroups.csv \
#--model_path models/20240417_cavalli_maha/20240417_VAE_idim12490_md2048_feat16mse_relu.pth