#!/bin/bash

md=$1
f=$2
lr=$3
#train_test_dir=$4

name="medullo_md${md}_f${f}_lr${lr}"

echo "#!/bin/bash"
echo "#SBATCH --job-name=\"$name\""
echo "#SBATCH --output=$(pwd)/err_out/VAE_$name_%j.out"
echo "#SBATCH --error=$(pwd)/err_out/VAE_$name_%j.err"
echo "#SBATCH --qos=bsc_ls"
echo "#SBATCH -c 40"
echo "#SBATCH --gres=gpu:1"
echo "#SBATCH --time=00-01:00:00"
echo "#SBATCH -D $(pwd)"
echo "module load intel impi mkl hdf5 python"
echo "python python_VAE.py --md $md --f $f --lr $lr \
--path_rnaseq ../data/interim/20240311_all_together/all_together_maha.csv \
--path_clinical ../data/interim/20240311_all_together/groups_all_together.csv \
--save_model False \
--model_type CVAE \
--clinical_train True \
--weightedrandomsampler False"

# Create the corresponding batch files:
#for i in 256 512 1024 2048 4096; do for j in 16 32 64 128 256 512; do for k in 0.0001; do ./job_VAE_w_classification $i $j $k > VAE_jobs/retraining_md${i}_f${j}_lr${k}.cmd; done; done; done
# Single job:
# ./job_VAE 1024 512 0.0001 > VAE_jobs/retraining_md1024_f512_lr0.0001.cmd

# ./job_VAE 1024 32 0.0001 ../data/interim/20240123_train_test_ductal/ > VAE_jobs/retraining_md1024_f$32_lr0.0001.cmd

# To send them all to the queue:
# for i in VAE_jobs/*; do echo $i; sbatch $i; done
