#!/bin/bash

md=$1
f=$2
lr=$3
data_path=$4
metadata_path=$5
save_path=$6
model_path=$7
batch_size=$8

name="medullo_md${md}_f${f}_lr${lr}"

echo "#!/bin/bash"
echo "#SBATCH --job-name=\"$name\""
echo "#SBATCH -A bsc20"
echo "#SBATCH --qos=acc_bscls"
echo "#SBATCH --output=$(pwd)/err_out/VAE_$name_%j.out"
echo "#SBATCH --error=$(pwd)/err_out/VAE_$name_%j.err"
echo "#SBATCH -c 20"
echo "#SBATCH --gres=gpu:1"
echo "#SBATCH --time=00-01:00:00"
echo "#SBATCH -D $(pwd)"
echo "#SBATCH  --hint=nomultithread"
echo "module load intel impi mkl hdf5 python"
echo "PYTHONPATH=\$PYTHONPATH:."
echo "python src/python_VAE.py --md $md --f $f --lr $lr --path_rnaseq $data_path --path_clinical $metadata_path --save_path $save_path --save_model --save_model_path $model_path --batch_size $batch_size"

# Create the corresponding batch files:
#for i in 256 512 1024 2048 4096; do for j in 16 32 64 128 256 512; do for k in 0.00001 0.0001 0.001; do ./job_VAE $i $j $k > VAE_jobs/retraining_md${i}_f${j}_lr${k}.cmd; done; done; done
# Single job:
# ./job_VAE 1024 512 0.0001 > VAE_jobs/retraining_md1024_f512_lr0.0001.cmd

# ./job_VAE 1024 32 0.0001 ../data/interim/20240123_train_test_ductal/ > VAE_jobs/retraining_md1024_f$32_lr0.0001.cmd

# To send them all to the queue:
# for i in VAE_jobs/*; do echo $i; sbatch $i; done
