#!/bin/bash

#SBATCH -A bsc20
#SBATCH --job-name=preprocessing
#SBATCH --output=err_out/preprocessing_%j.out
#SBATCH --error=err_out/preprocessing_%j.err
#SBATCH --qos=gp_bscls
#SBATCH -c 16
#SBATCH --time=00-00:15:00
#SBATCH -D .

data_path=$1
metadata_path=$2
save_path=$3
module load intel impi mkl hdf5 python
python src/preprocessing.py --data_path $data_path \
							--metadata_path $metadata_path \
							--save_path $save_path \
							--per 0.2 \
							--cutoff 0.1 \
							--alpha 0.05