#!/bin/bash

#SBATCH -A bsc20
#SBATCH --job-name=knn
#SBATCH --output=err_out/knn_%j.out
#SBATCH --error=err_out/knn_%j.err
#SBATCH --qos=gp_bscls
#SBATCH -c 16
#SBATCH --time=00-02:00:00
#SBATCH -D .

data_path=$1
metadata_path=$2
save_path=$3


module load intel impi mkl hdf5 python
PYTHONPATH=$PYTHONPATH:.
python src/clustering_g3g4.py --data_path $data_path \
                              --metadata_path $metadata_path  \
                              --save_path $save_path
## Old version: included paths to models
#data_path=$1
#metadata_path=$2
#vae_path=$3
#recnet_path=$4
#output_rec_path=$5
#save_path=$6
#python src/clustering_g3g4.py --data_path $data_path \
#                              --metadata_path $metadata_path  \
#                              --model_path $vae_path \
#                              --network_model_path $recnet_path \
#                              --recnet_hyperparams_path $output_rec_path \
#                              --save_path $save_path