#!/bin/bash

#SBATCH -A bsc20
#SBATCH --job-name=checkmodel
#SBATCH --output=err_out/checkmodel_%j.out
#SBATCH --error=err_out/checkmodel_%j.err
#SBATCH --qos=gp_bscls
#SBATCH -c 16
#SBATCH --time=00-00:15:00
#SBATCH -D .

save_path=$1
data_path=$2
clinical_path=$3
module load intel impi mkl hdf5 python
PYTHONPATH=$PYTHONPATH:.
python src/models/check_model.py --save_path $save_path \
                                 --rnaseq_path $data_path \
                                 --clinical_path $clinical_path