#!/bin/bash

#SBATCH -A bsc20
#SBATCH --job-name=adjustrec
#SBATCH --output=err_out/adjustrec_%j.out
#SBATCH --error=err_out/adjustrec_%j.err
#SBATCH --qos=acc_bscls
#SBATCH -c 20
#SBATCH --gres=gpu:1
#SBATCH --time=01-00:00:00
#SBATCH -D .

# add a variable today with the date in format YYYYMMDD
model_path=$1
data_path=$2
clinical_path=$3
output_path=$4
output_recnet_path=$5
module load intel impi mkl hdf5 python
PYTHONPATH=$PYTHONPATH:.
python src/adjust_reconstruction.py --model_path $model_path \
                                    --data_path $data_path \
                                    --clinical_path $clinical_path \
                                    --output_path $output_path \
                                    --output_recnet_path $output_recnet_path \
                                    --batch_size 8 \
                                    --test_size 0.2 \
                                    --seed 2023 \
                                    --epochs 1000 \
                                    --lr 0.0001 \
                                    --n_trials 100